// Plans & credits — the ONE place that says in words what a plan includes.
//
// Numbers (price, quota, projects, credits, cadence, library cap, engines)
// come from the `plans` table (the Stripe catalogue mirrors it); the words
// come from here. Both /pricing and the dashboard billing modal render from
// this file, so the public quote and the in-app quote can never disagree.
// Client-safe: no server imports.

export type PlanLang = 'zh' | 'en' | 'vi';
export type PlanFamily = 'basic' | 'standard' | 'premium';

export interface PlanRowLike {
  id: string;
  name: string;
  region?: string | null;
  price_usd_month: number | null;
  monthly_scan_quota: number;
  max_projects: number;
  included_credits_monthly?: number | null;
  scan_cadence?: string | null;
  prompt_library_cap?: number | null;
  sampled_per_scan?: number | null;
  engines?: number | null;
  features?: Record<string, unknown> | null;
  stripe_price_id?: string | null;
}

export function planFamily(id: string): PlanFamily {
  if (id.endsWith('premium')) return 'premium';
  if (id.endsWith('standard')) return 'standard';
  return 'basic';
}

export function readPlanLang(): PlanLang {
  try {
    const l = localStorage.getItem('memecmo-uilang');
    if (l === 'zh' || l === 'en' || l === 'vi') return l;
  } catch { /* SSR / privacy mode */ }
  return 'zh';
}

export function fmtUsd(n: number | null | undefined): string {
  if (n == null) return '';
  return `US$${n.toLocaleString('en-US')}`;
}

// ── per-family words ─────────────────────────────────────────────────────────
interface FamilyCopy {
  name: string;
  tagline: string;
  audience: string;
  service: string;      // human service line
  onboarding: string;
}

export const FAMILY_COPY: Record<PlanLang, Record<PlanFamily, FamilyCopy>> = {
  zh: {
    basic: {
      name: 'Starter',
      tagline: '先知道 AI 有没有提到你',
      audience: '一个品牌、一个市场;想用标准指标看清现状,再决定投入。',
      service: '自助服务:报告与提醒由平台自动生成;技术问题邮件支持,2 个工作日内回复。',
      onboarding: '无建档费:品牌画像与提示词库由智能体自动建立,首次完整扫描即 Day-0 基线。',
    },
    standard: {
      name: 'Growth',
      tagline: '有团队自己改内容,需要数据追踪成效',
      audience: '品牌方或代理商团队;要在同一冻结面板上看每次修复前后到底动了什么。',
      service: '自助服务:报告与提醒由平台自动生成;技术问题邮件支持,2 个工作日内回复。',
      onboarding: '无建档费:品牌画像与提示词库由智能体自动建立,首次完整扫描即 Day-0 基线。',
    },
    premium: {
      name: 'Scale',
      tagline: '多品牌 / 多产品线 / 多市场,需要我们一起规划与执行',
      audience: '集团品牌与媒体集团;每周完整扫描,不限席位,数据可导出。',
      service: '专属顾问:每月顾问会议、修复建议清单、季度管理层汇报;运行队列优先。',
      onboarding: '含首次解读会:与你的团队一起确认品牌事实、题库与竞对集,再开始计量。',
    },
  },
  en: {
    basic: {
      name: 'Starter',
      tagline: 'Find out whether AI mentions you at all',
      audience: 'One brand, one market. See the baseline in standard metrics before you commit.',
      service: 'Self-serve: reports and alerts are generated by the platform; email support for technical issues within 2 working days.',
      onboarding: 'No setup fee: the agents build the brand profile and prompt library; the first full scan is your Day-0 baseline.',
    },
    standard: {
      name: 'Growth',
      tagline: 'Your team fixes the content; you need the data to prove it worked',
      audience: 'Brand or agency teams that want before/after on the same frozen prompt panel.',
      service: 'Self-serve: reports and alerts are generated by the platform; email support for technical issues within 2 working days.',
      onboarding: 'No setup fee: the agents build the brand profile and prompt library; the first full scan is your Day-0 baseline.',
    },
    premium: {
      name: 'Scale',
      tagline: 'Many brands, product lines or markets — planned and executed with us',
      audience: 'Group brands and media groups: weekly full scans, unlimited seats, data export.',
      service: 'Dedicated advisor: monthly advisory call, prioritized fix list, quarterly leadership readout; priority run queue.',
      onboarding: 'Kick-off session included: we confirm brand facts, prompt panel and competitor set with your team before measuring.',
    },
  },
  vi: {
    basic: {
      name: 'Starter',
      tagline: 'Biết trước AI có nhắc đến bạn hay không',
      audience: 'Một thương hiệu, một thị trường. Xem đường cơ sở bằng chỉ số chuẩn trước khi đầu tư.',
      service: 'Tự phục vụ: báo cáo và cảnh báo do nền tảng tự tạo; hỗ trợ kỹ thuật qua email trong 2 ngày làm việc.',
      onboarding: 'Không phí khởi tạo: agent tự xây hồ sơ thương hiệu và thư viện câu hỏi; lần quét đầy đủ đầu tiên là đường cơ sở Ngày 0.',
    },
    standard: {
      name: 'Growth',
      tagline: 'Đội của bạn tự sửa nội dung, cần dữ liệu để chứng minh hiệu quả',
      audience: 'Đội thương hiệu hoặc agency muốn so sánh trước/sau trên cùng một bộ câu hỏi cố định.',
      service: 'Tự phục vụ: báo cáo và cảnh báo do nền tảng tự tạo; hỗ trợ kỹ thuật qua email trong 2 ngày làm việc.',
      onboarding: 'Không phí khởi tạo: agent tự xây hồ sơ thương hiệu và thư viện câu hỏi; lần quét đầy đủ đầu tiên là đường cơ sở Ngày 0.',
    },
    premium: {
      name: 'Scale',
      tagline: 'Nhiều thương hiệu / dòng sản phẩm / thị trường, cùng chúng tôi lập kế hoạch và thực thi',
      audience: 'Tập đoàn và nhóm truyền thông: quét đầy đủ hàng tuần, không giới hạn tài khoản, xuất dữ liệu.',
      service: 'Cố vấn chuyên trách: họp tư vấn hàng tháng, danh sách sửa lỗi ưu tiên, báo cáo lãnh đạo hàng quý; hàng đợi chạy ưu tiên.',
      onboarding: 'Bao gồm buổi khởi động: cùng đội của bạn xác nhận dữ kiện thương hiệu, bộ câu hỏi và danh sách đối thủ trước khi đo.',
    },
  },
};

// ── service items derived from the row ───────────────────────────────────────
export interface ServiceGroup { title: string; items: string[] }

const CADENCE: Record<PlanLang, Record<string, string>> = {
  zh: { monthly: '每月 1 次', biweekly: '每两周 1 次', weekly: '每周 1 次' },
  en: { monthly: 'monthly', biweekly: 'every two weeks', weekly: 'weekly' },
  vi: { monthly: 'mỗi tháng 1 lần', biweekly: 'hai tuần 1 lần', weekly: 'mỗi tuần 1 lần' },
};

export function planServiceGroups(p: PlanRowLike, lang: PlanLang): ServiceGroup[] {
  const f = planFamily(p.id);
  const feat = (p.features ?? {}) as Record<string, unknown>;
  const engines = p.engines ?? (feat.engines as number) ?? 4;
  const real = engines >= 5 || !!feat.real_surface;
  const lib = p.prompt_library_cap ?? 60;
  const sampled = p.sampled_per_scan ?? 12;
  const queries = sampled * engines;
  const cadence = p.scan_cadence ?? 'monthly';
  const weeklyReports = (feat.reports as string) === 'weekly';
  const credits = p.included_credits_monthly ?? 0;
  const distribute = !!feat.distribute;
  const encyclopedia = !!feat.encyclopedia;
  const priority = !!feat.priority;
  const cad = CADENCE[lang][cadence] ?? cadence;

  if (lang === 'zh') {
    return [
      { title: '测量', items: [
        real ? '5 个 AI 引擎:ChatGPT · Gemini · Claude · Perplexity · Google AI Overview(真实搜索页,按市场定位)' : '4 个 AI 引擎:ChatGPT · Gemini · Claude · Perplexity(不含 Google AI Overview)',
        `提示词库上限 ${lib} 条(按买家旅程 5 阶段生成,20 条重点题每次必测);每次扫描抽样 ${sampled} 条 × ${engines} 引擎 ≈ ${queries} 次真实提问`,
        `定期扫描 ${cad},由平台自动执行并计入额度;每月计量扫描上限 ${p.monthly_scan_quota} 次(含定期扫描)`,
        '五个标准指标逐引擎给出并附分子分母:出现率 · 声量份额 · 显著度 · 情感 · 引用;另有首位推荐率与高意图缺口清单',
        'AI 引用来源排行 + 被引页面读取(结构、更新日期、schema)→ 你市场的引用画像',
        'Day-0 基线、出现率走势、月度环比;竞对集与提示词库可编辑,历史扫描永不改动',
      ] },
      { title: '交付', items: [
        weeklyReports ? '每周自动摘要邮件 + 每月报告(按项目阶段解读;掉分即时告警)' : '每月报告(按项目阶段解读;掉分即时告警)',
        '品牌画像(公开事实库)与标准答案库(市场语言 + 英文)',
        distribute ? '内容优化 · 官网改造(JSON-LD)· 媒体投放包(按引用排行选目标,排除竞对域名)' : '内容优化 · 官网改造(JSON-LD)',
        encyclopedia ? '百科评估与合规提交路径' : '',
        '所有交付物可编辑、可复制、可导出 PDF;你的人工修改在重跑后保留',
        '行动记录与自动核验:登记已发布的页面/文章,平台抓取并在后续扫描中归因',
      ].filter(Boolean) },
      { title: '团队', items: [
        `${p.max_projects} 个项目(1 项目 = 1 品牌 × 1 市场)`,
        '席位不限:admin / editor / viewer 三种角色,不按人头收费',
        '界面语言中 / EN / VN;交付物跟随市场语言,可页内翻译阅读',
      ] },
      { title: 'Credit 与服务', items: [
        credits > 0 ? `每月赠送 ${credits} credit(约 ${Math.floor(credits / 25)} 次手动扫描),定期扫描永不扣 credit` : '不含月度 credit;定期扫描永不扣 credit,手动加跑按 credit 计',
        FAMILY_COPY.zh[f].service,
        FAMILY_COPY.zh[f].onboarding,
        priority ? '运行队列优先;数据导出' : '',
      ].filter(Boolean) },
    ];
  }
  if (lang === 'vi') {
    return [
      { title: 'Đo lường', items: [
        real ? '5 AI engine: ChatGPT · Gemini · Claude · Perplexity · Google AI Overview (trang tìm kiếm thật, định vị theo thị trường)' : '4 AI engine: ChatGPT · Gemini · Claude · Perplexity (không gồm Google AI Overview)',
        `Thư viện tối đa ${lib} câu hỏi (5 giai đoạn hành trình mua, 20 câu trọng điểm luôn được đo); mỗi lần quét lấy mẫu ${sampled} câu × ${engines} engine ≈ ${queries} lượt hỏi thật`,
        `Quét định kỳ ${cad}, nền tảng tự chạy và tính vào hạn mức; tối đa ${p.monthly_scan_quota} lần quét tính phí mỗi tháng (gồm quét định kỳ)`,
        'Năm chỉ số chuẩn theo từng engine, luôn kèm tử số/mẫu số: tỷ lệ xuất hiện · thị phần nhắc tên · độ nổi bật · cảm xúc · trích dẫn; thêm tỷ lệ đề xuất đầu tiên và danh sách khoảng trống ý định cao',
        'Xếp hạng nguồn AI trích dẫn + đọc các trang được trích (cấu trúc, ngày cập nhật, schema) → hồ sơ trích dẫn của thị trường bạn',
        'Đường cơ sở Ngày 0, xu hướng tỷ lệ xuất hiện, so sánh theo tháng; bộ đối thủ và thư viện câu hỏi chỉnh sửa được, lịch sử quét không bao giờ bị sửa',
      ] },
      { title: 'Bàn giao', items: [
        weeklyReports ? 'Email tóm tắt tự động hàng tuần + báo cáo hàng tháng (diễn giải theo giai đoạn dự án; cảnh báo ngay khi sụt điểm)' : 'Báo cáo hàng tháng (diễn giải theo giai đoạn dự án; cảnh báo ngay khi sụt điểm)',
        'Hồ sơ thương hiệu (dữ kiện công khai) và thư viện câu trả lời chuẩn (ngôn ngữ thị trường + tiếng Anh)',
        distribute ? 'Tối ưu nội dung · nâng cấp website (JSON-LD) · bộ đăng tải truyền thông (chọn mục tiêu theo xếp hạng trích dẫn, loại trừ tên miền đối thủ)' : 'Tối ưu nội dung · nâng cấp website (JSON-LD)',
        encyclopedia ? 'Đánh giá bách khoa và lộ trình nộp hợp quy' : '',
        'Mọi sản phẩm chỉnh sửa, sao chép, xuất PDF được; chỉnh sửa thủ công của bạn được giữ nguyên sau khi chạy lại',
        'Nhật ký hành động và tự xác minh: ghi lại trang/bài đã đăng, nền tảng tải về và quy kết trong các lần quét sau',
      ].filter(Boolean) },
      { title: 'Đội ngũ', items: [
        `${p.max_projects} dự án (1 dự án = 1 thương hiệu × 1 thị trường)`,
        'Không giới hạn tài khoản: ba vai trò admin / editor / viewer, không tính phí theo người',
        'Giao diện 中文 / EN / VN; sản phẩm theo ngôn ngữ thị trường, dịch đọc ngay trên trang',
      ] },
      { title: 'Credit & dịch vụ', items: [
        credits > 0 ? `Tặng ${credits} credit mỗi tháng (≈ ${Math.floor(credits / 25)} lần quét thủ công); quét định kỳ không bao giờ trừ credit` : 'Không kèm credit hàng tháng; quét định kỳ không trừ credit, chạy thủ công tính theo credit',
        FAMILY_COPY.vi[f].service,
        FAMILY_COPY.vi[f].onboarding,
        priority ? 'Hàng đợi chạy ưu tiên; xuất dữ liệu' : '',
      ].filter(Boolean) },
    ];
  }
  return [
    { title: 'Measurement', items: [
      real ? '5 AI engines: ChatGPT · Gemini · Claude · Perplexity · Google AI Overview (the real search page, location-targeted)' : '4 AI engines: ChatGPT · Gemini · Claude · Perplexity (no Google AI Overview)',
      `Prompt library up to ${lib} questions (5 buyer-journey stages, the 20 key prompts measured every time); each scan samples ${sampled} prompts × ${engines} engines ≈ ${queries} real queries`,
      `Scheduled scans ${cad}, run by the platform and counted in the quota; up to ${p.monthly_scan_quota} metered scans per month (scheduled ones included)`,
      'Five standard metrics per engine, each with its numerator and denominator: presence · share of voice · prominence · sentiment · citation; plus top-of-mind rate and the high-intent gap list',
      'Ranking of the sources AI cites + fetching of the cited pages (structure, update date, schema) → the citation profile of your market',
      'Day-0 baseline, presence trend, month-over-month; editable competitor set and prompt library, past scans never rewritten',
    ] },
    { title: 'Deliverables', items: [
      weeklyReports ? 'Weekly automated digest email + monthly report (stage-aware reading; instant alert on drops)' : 'Monthly report (stage-aware reading; instant alert on drops)',
      'Brand profile (public fact base) and standard-answer library (market language + English)',
      distribute ? 'Content optimization · site upgrade (JSON-LD) · media placement kit (targets picked from the citation ranking, competitor domains excluded)' : 'Content optimization · site upgrade (JSON-LD)',
      encyclopedia ? 'Encyclopedia assessment with a compliant submission path' : '',
      'Every deliverable is editable, copyable and exportable as PDF; your manual edits survive re-runs',
      'Action log with automatic verification: register what went live, the platform fetches it and attributes it in later scans',
    ].filter(Boolean) },
    { title: 'Team', items: [
      `${p.max_projects} project${p.max_projects > 1 ? 's' : ''} (1 project = 1 brand × 1 market)`,
      'Unlimited seats: admin / editor / viewer roles, never billed per head',
      'Interface in 中文 / EN / VN; deliverables follow the market language, translate in place to read',
    ] },
    { title: 'Credits & service', items: [
      credits > 0 ? `${credits} credits granted monthly (≈ ${Math.floor(credits / 25)} manual scans); scheduled scans never consume credits` : 'No monthly credits; scheduled scans never consume credits, manual runs are paid in credits',
      FAMILY_COPY.en[f].service,
      FAMILY_COPY.en[f].onboarding,
      priority ? 'Priority run queue; data export' : '',
    ].filter(Boolean) },
  ];
}

/** Short lines for the in-app billing modal (one language, no echo). */
export function planShortLines(p: PlanRowLike, lang: PlanLang): string[] {
  const feat = (p.features ?? {}) as Record<string, unknown>;
  const engines = p.engines ?? (feat.engines as number) ?? 4;
  const cad = CADENCE[lang][p.scan_cadence ?? 'monthly'] ?? p.scan_cadence ?? '';
  const credits = p.included_credits_monthly ?? 0;
  const weekly = (feat.reports as string) === 'weekly';
  if (lang === 'zh') return [
    `定期扫描 ${cad} · 每月计量扫描上限 ${p.monthly_scan_quota} 次`,
    `${engines} 个 AI 引擎${engines >= 5 ? '(含真实 Google AI Overview)' : ''} · 提示词库 ${p.prompt_library_cap ?? 60} 条`,
    `${p.max_projects} 个项目 · 席位不限`,
    weekly ? '每周摘要邮件 + 月度报告' : '月度报告',
    credits > 0 ? `每月赠送 ${credits} credit` : '不含月度 credit',
  ];
  if (lang === 'vi') return [
    `Quét định kỳ ${cad} · tối đa ${p.monthly_scan_quota} lần quét tính phí/tháng`,
    `${engines} AI engine${engines >= 5 ? ' (gồm Google AI Overview thật)' : ''} · thư viện ${p.prompt_library_cap ?? 60} câu`,
    `${p.max_projects} dự án · không giới hạn tài khoản`,
    weekly ? 'Email tóm tắt hàng tuần + báo cáo tháng' : 'Báo cáo tháng',
    credits > 0 ? `Tặng ${credits} credit mỗi tháng` : 'Không kèm credit hàng tháng',
  ];
  return [
    `Scheduled scans ${cad} · up to ${p.monthly_scan_quota} metered scans / month`,
    `${engines} AI engines${engines >= 5 ? ' (incl. real Google AI Overview)' : ''} · prompt library ${p.prompt_library_cap ?? 60}`,
    `${p.max_projects} project${p.max_projects > 1 ? 's' : ''} · unlimited seats`,
    weekly ? 'Weekly digest email + monthly report' : 'Monthly report',
    credits > 0 ? `${credits} credits granted monthly` : 'No monthly credits',
  ];
}

// ── credits, rules, partners, FAQ (words only) ───────────────────────────────
export interface CreditCopy {
  title: string; lead: string;
  costsTitle: string; costs: [string, string][];
  packsTitle: string; packsNote: string;
  rules: [string, string][];
}

export const CREDIT_COPY: Record<PlanLang, CreditCopy> = {
  zh: {
    title: 'Credit:买的是「立即触发权」',
    lead: '合同节奏内的定期扫描与报告永远不扣 credit。只有你自己点「运行」的即时加跑才计 credit——语料没变时反复加扫只会把噪音当信号,所以我们把「等不及」单独定价,而不是抬高月费。',
    costsTitle: '每次手动运行的 credit',
    costs: [
      ['完整扫描(发现 → 监测 → 报告)', '25'],
      ['监测(单独重测 5 引擎)', '25'],
      ['报告重写', '10'],
      ['品牌画像 · 发现 · 标准答案', '10'],
      ['内容优化 · 官网改造 · 媒体投放 · 百科', '10'],
    ],
    packsTitle: 'Credit 包(一次性购买,可开票)',
    packsNote: '标价 US$1 / credit,大包附加赠送;由 Stripe 收款,购买后即时入账。',
    rules: [
      ['两个池子', '赠送池(套餐月度内含、活动赠送)优先扣减、不开票;购买池(credit 包)可开票。余额 = 两池之和,工作区右栏随时可见。'],
      ['失败不收费', '任何一次运行失败,扣掉的 credit 自动原路退回——客户绝不为没送达的交付物付费。'],
      ['月度发放', '套餐内含 credit 于每月 1 日发放到赠送池;渠道伙伴的售前演示扫描由运营方以赠送 credit 覆盖,不占客户的购买池。'],
      ['运营方运行', 'MemeCMO 运营人员为你执行的交付性运行不扣 credit,也不占你的扫描额度。'],
    ],
  },
  en: {
    title: 'Credits buy the right to run something now',
    lead: 'Scheduled scans and reports inside your plan never consume credits. Only a run you trigger yourself is paid in credits. Re-scanning while the corpus has not changed only turns noise into "signal", so we price impatience separately instead of raising the monthly fee.',
    costsTitle: 'Credits per manual run',
    costs: [
      ['Full scan (discovery → monitor → report)', '25'],
      ['Monitor (re-measure the 5 engines)', '25'],
      ['Report rewrite', '10'],
      ['Brand profile · discovery · standard answers', '10'],
      ['Content · site upgrade · media placement · encyclopedia', '10'],
    ],
    packsTitle: 'Credit packs (one-time, invoiceable)',
    packsNote: 'List price US$1 per credit with a bonus on larger packs; paid via Stripe and credited instantly.',
    rules: [
      ['Two pools', 'The granted pool (plan allowance, promotions) is spent first and is never invoiced; the purchased pool (packs) is invoiceable. Balance = both pools, visible in the workspace rail.'],
      ['Failed runs are free', 'Credits spent on a run that fails are refunded automatically to the pool they came from. A client never pays for a deliverable that did not arrive.'],
      ['Monthly allowance', 'Plan credits land in the granted pool on the 1st of each month. Partner pre-sales demo scans are covered by operator-granted credits, not the client\'s purchased pool.'],
      ['Operator runs', 'Runs performed for you by MemeCMO staff as part of delivery consume neither credits nor your scan quota.'],
    ],
  },
  vi: {
    title: 'Credit mua quyền chạy ngay lập tức',
    lead: 'Quét và báo cáo định kỳ trong gói không bao giờ trừ credit. Chỉ những lần bạn tự bấm chạy mới tính credit. Quét lại khi nội dung chưa đổi chỉ biến nhiễu thành "tín hiệu", nên chúng tôi định giá riêng cho sự sốt ruột thay vì nâng phí tháng.',
    costsTitle: 'Credit cho mỗi lần chạy thủ công',
    costs: [
      ['Quét đầy đủ (khám phá → giám sát → báo cáo)', '25'],
      ['Giám sát (đo lại 5 engine)', '25'],
      ['Viết lại báo cáo', '10'],
      ['Hồ sơ thương hiệu · khám phá · câu trả lời chuẩn', '10'],
      ['Nội dung · nâng cấp website · đăng tải · bách khoa', '10'],
    ],
    packsTitle: 'Gói credit (mua một lần, có hóa đơn)',
    packsNote: 'Giá niêm yết US$1 / credit, gói lớn được tặng thêm; thanh toán qua Stripe, cộng ngay vào tài khoản.',
    rules: [
      ['Hai quỹ', 'Quỹ tặng (credit trong gói, khuyến mãi) trừ trước và không xuất hóa đơn; quỹ mua (gói credit) có hóa đơn. Số dư = tổng hai quỹ, luôn thấy ở cột phải workspace.'],
      ['Chạy lỗi không mất phí', 'Credit của lần chạy thất bại được hoàn tự động về đúng quỹ. Khách hàng không bao giờ trả tiền cho sản phẩm chưa được bàn giao.'],
      ['Cấp hàng tháng', 'Credit trong gói được cấp vào quỹ tặng ngày 1 hàng tháng. Quét demo bán hàng của đối tác do vận hành cấp credit tặng, không dùng quỹ mua của khách.'],
      ['Nhân sự vận hành chạy', 'Các lần chạy do nhân sự MemeCMO thực hiện cho bạn trong quá trình bàn giao không trừ credit và không tính vào hạn mức quét.'],
    ],
  },
};

export interface RulesCopy { title: string; lead: string; rows: [string, string][] }

export const RULES_COPY: Record<PlanLang, RulesCopy> = {
  zh: {
    title: '计费规则与承诺边界',
    lead: '写在这里的,就是签约时的条款;没写的,不承诺。',
    rows: [
      ['计价与付款', '以美元计价,月费按月预付(Stripe 自动续费,可在工作台管理付款方式与发票)。港币或对公转账付款按签约日汇率折算,服务期内不变。'],
      ['年付', '一次预付 12 个月按 10 个月月费收取;提前终止时已用月份按标准月费结算,余额 30 日内退还。'],
      ['最短期限', 'Starter 按月续期。Growth 与 Scale 最短 3 个月——出现率需要至少三期数据才能判读趋势与修复成效。'],
      ['终止', '任一方提前 30 日书面通知即可终止;最短期限内的通知在期满时生效。已支付的当期月费不退,其后不再收费。'],
      ['升级 / 降级', '下一个服务期生效,升级只补差额。降级后走势按两个套餐的共同题目计算,并在报告中注明。'],
      ['引擎中断', '某个 AI 引擎某期不可用,报告注明并以其余引擎计算;整期有效回答不足九成,该期不计费或顺延一期,由你选择。'],
      ['价格调整', '调整月费须提前 30 日书面通知;已预付月份与年付期间不受影响。'],
      ['数据归属', '品牌档案、商标与你提供的资料归你;平台、题库方法、判定与评分规则归 MemeCMO。报告与看板授权你及代表你的代理商作内部用途。服务终止后 12 个月内可要求导出全部历史;欠费只暂停扫描,看板与历史保留。'],
      ['对外数据', '未经你逐次书面同意,不以可识别你的方式公开或演示你的数据。行业研究只用去标识化的汇总,任何公开数字来自不少于 5 个品牌。'],
      ['我们不承诺的', '不承诺任何引擎的排名、推荐或提及次数,不承诺销售额。AI 回答具随机性,我们以多题多次提问降低偶然性,但单次回答不代表整体。答案准确度只对照你官网已公开的事实。'],
    ],
  },
  en: {
    title: 'Billing rules and the promise boundary',
    lead: 'What is written here is what you sign; what is not written is not promised.',
    rows: [
      ['Currency & payment', 'Priced in USD, monthly fees prepaid (Stripe auto-renews; manage payment method and invoices in the dashboard). HKD or bank transfer is converted at the contract-date rate and fixed for the term.'],
      ['Annual', '12 months prepaid are charged as 10 monthly fees. On early termination, months used are settled at the standard rate and the balance refunded within 30 days.'],
      ['Minimum term', 'Starter renews month to month. Growth and Scale have a 3-month minimum: presence needs at least three periods before a trend or a fix effect can be read.'],
      ['Termination', 'Either side may terminate with 30 days\' written notice; notice inside the minimum term takes effect when it ends. The current prepaid month is not refunded; nothing further is charged.'],
      ['Upgrade / downgrade', 'Takes effect next service period; an upgrade only pays the difference. After a downgrade the trend is computed on the prompts both plans share, and the report says so.'],
      ['Engine outage', 'If an engine is unavailable for a period, the report says so and the rest are used. If valid answers fall below 90% for the whole period, that period is not billed or is deferred, your choice.'],
      ['Price changes', 'At least 30 days\' written notice; prepaid months and annual terms are unaffected.'],
      ['Who owns what', 'Your brand profile, marks and material stay yours; the platform, prompt method, judging and scoring rules are MemeCMO\'s. Reports and dashboards are licensed to you and to agencies acting for you, for internal use. You can export your full history up to 12 months after termination; unpaid status pauses scans only, the dashboard and history stay.'],
      ['Public data', 'Your data is never published or demoed in an identifiable form without your written consent, case by case. Industry research uses de-identified aggregates only, and any public figure comes from at least 5 brands.'],
      ['What we do not promise', 'No promise of ranking, recommendation or mention counts on any engine, and no promise of sales. AI answers are stochastic; many prompts asked many times reduce chance, but no single answer stands for the whole. Answer accuracy is checked only against facts already public on your site.'],
    ],
  },
  vi: {
    title: 'Quy tắc tính phí và ranh giới cam kết',
    lead: 'Những gì viết ở đây là điều bạn ký; điều không viết là điều không hứa.',
    rows: [
      ['Tiền tệ & thanh toán', 'Tính bằng USD, phí tháng trả trước (Stripe tự gia hạn; quản lý phương thức thanh toán và hóa đơn trong bảng điều khiển). Thanh toán bằng HKD hoặc chuyển khoản quy đổi theo tỷ giá ngày ký, cố định trong kỳ.'],
      ['Trả theo năm', 'Trả trước 12 tháng tính bằng 10 tháng phí. Chấm dứt sớm: tháng đã dùng tính theo giá chuẩn, phần còn lại hoàn trong 30 ngày.'],
      ['Thời hạn tối thiểu', 'Starter gia hạn theo tháng. Growth và Scale tối thiểu 3 tháng: tỷ lệ xuất hiện cần ít nhất ba kỳ dữ liệu mới đọc được xu hướng và hiệu quả sửa lỗi.'],
      ['Chấm dứt', 'Mỗi bên có thể chấm dứt bằng thông báo bằng văn bản trước 30 ngày; thông báo trong thời hạn tối thiểu có hiệu lực khi hết hạn. Phí tháng hiện tại đã trả không hoàn; không thu thêm sau đó.'],
      ['Nâng / hạ gói', 'Có hiệu lực từ kỳ dịch vụ tiếp theo; nâng gói chỉ bù phần chênh lệch. Sau khi hạ gói, xu hướng được tính trên các câu hỏi chung của hai gói và báo cáo ghi rõ.'],
      ['Gián đoạn engine', 'Nếu một engine không dùng được trong một kỳ, báo cáo ghi chú và tính theo các engine còn lại. Nếu câu trả lời hợp lệ cả kỳ dưới 90%, kỳ đó không tính phí hoặc lùi một kỳ, do bạn chọn.'],
      ['Điều chỉnh giá', 'Thông báo bằng văn bản trước ít nhất 30 ngày; các tháng đã trả trước và kỳ trả năm không bị ảnh hưởng.'],
      ['Quyền sở hữu dữ liệu', 'Hồ sơ thương hiệu, nhãn hiệu và tài liệu bạn cung cấp thuộc về bạn; nền tảng, phương pháp bộ câu hỏi, quy tắc chấm điểm thuộc MemeCMO. Báo cáo và bảng điều khiển được cấp phép cho bạn và agency đại diện bạn dùng nội bộ. Có thể xuất toàn bộ lịch sử trong 12 tháng sau khi chấm dứt; nợ phí chỉ tạm dừng quét, bảng điều khiển và lịch sử vẫn giữ.'],
      ['Dữ liệu công khai', 'Không công bố hay demo dữ liệu của bạn dưới dạng nhận diện được nếu chưa có đồng ý bằng văn bản từng lần. Nghiên cứu ngành chỉ dùng số liệu tổng hợp đã ẩn danh; mọi con số công bố đến từ ít nhất 5 thương hiệu.'],
      ['Điều chúng tôi không hứa', 'Không hứa thứ hạng, đề xuất hay số lần nhắc tên trên bất kỳ engine nào, không hứa doanh số. Câu trả lời AI có tính ngẫu nhiên; hỏi nhiều câu nhiều lần giảm sai số nhưng một câu trả lời đơn lẻ không đại diện toàn bộ. Độ chính xác chỉ đối chiếu với dữ kiện đã công khai trên website của bạn.'],
    ],
  },
};

export interface PartnerCopy { title: string; body: string; cta: string }
export const PARTNER_COPY: Record<PlanLang, PartnerCopy> = {
  zh: { title: '代理商与媒体集团', body: '每个客户一个独立工作区(行级数据隔离)、汇总报告、席位不限、批发价;客户由你开通并邀请,由总部审批激活。售前演示扫描由运营方以赠送 credit 覆盖。', cta: '谈渠道合作' },
  en: { title: 'Agencies and media groups', body: 'A separate workspace per client (row-level data isolation), rollup reports, unlimited seats, wholesale pricing. You provision and invite clients; head office approves and activates. Pre-sales demo scans are covered by operator-granted credits.', cta: 'Talk about partnership' },
  vi: { title: 'Agency và nhóm truyền thông', body: 'Mỗi khách hàng một workspace riêng (cách ly dữ liệu theo hàng), báo cáo tổng hợp, không giới hạn tài khoản, giá sỉ. Bạn mở và mời khách hàng, trụ sở duyệt và kích hoạt. Quét demo bán hàng do vận hành cấp credit tặng.', cta: 'Trao đổi hợp tác kênh' },
};

export const PRICING_FAQ: Record<PlanLang, [string, string][]> = {
  zh: [
    ['为什么没有免费版?', '每次扫描都是真实的引擎调用费用。免费预览扫描(2 引擎 × 8 题)在注册时提供一次,足够看出 AI 有没有提到你;之后的每一次测量都以套餐或 credit 计,这样我们才能对每个数字负责。'],
    ['月度扫描额度和 credit 是什么关系?', '额度是每月计量扫描(完整扫描 / 监测)的上限,定期扫描也计入;credit 是手动触发的费用。定期扫描只占额度、不扣 credit;手动加跑既占额度也扣 credit。'],
    ['同一个品牌进两个市场怎么算?', '一个项目 = 一个品牌 × 一个市场。两个市场就是两个项目,各自有独立的提示词库、竞对集与分数——合并测会互相掩盖。'],
    ['修复项目(改官网、投稿、百科)包含在月费里吗?', '交付物(可发布的稿件、JSON-LD、投放包)包含;实际的发布、投稿与编辑协作由你的团队或代理商执行。Scale 的顾问会议帮你排优先级,不代替执行。'],
    ['怎样验收成效?', '题库冻结后,修复相关题目的出现率变化减去其余题目同期变化 = 修复成效;只把汇总后超过 10 个百分点的变化报告为成效。每一步都记在「行动记录」里,平台自动核验发布页并归因。'],
  ],
  en: [
    ['Why is there no free plan?', 'Every scan is a real engine call with a real cost. One free preview scan (2 engines × 8 prompts) at sign-up is enough to see whether AI mentions you; every measurement after that is paid by plan or credits, which is how we stay accountable for every number.'],
    ['How do the scan quota and credits relate?', 'The quota caps metered scans (full scan / monitor) per month, scheduled ones included; credits pay for manual triggers. Scheduled scans use quota only; a manual run uses quota and credits.'],
    ['One brand in two markets?', 'One project = one brand × one market. Two markets are two projects, each with its own prompt library, competitor set and scores; merging them would hide each other.'],
    ['Are fixes (site edits, placements, encyclopedia) included?', 'The deliverables are: publish-ready drafts, JSON-LD, placement kits. Publishing, pitching and editorial work are done by your team or agency. Scale\'s advisory call prioritizes; it does not replace execution.'],
    ['How is effect proven?', 'With the panel frozen, the presence change on the prompts a fix targeted minus the change on all other prompts = fix effect; only aggregated changes above 10 points are reported as effect. Every step is logged as an action, and the platform verifies the live page and attributes it.'],
  ],
  vi: [
    ['Vì sao không có gói miễn phí?', 'Mỗi lần quét là lượt gọi engine thật với chi phí thật. Một lần quét xem trước miễn phí (2 engine × 8 câu) khi đăng ký đủ để thấy AI có nhắc đến bạn không; mọi phép đo sau đó tính theo gói hoặc credit, nhờ vậy chúng tôi chịu trách nhiệm cho từng con số.'],
    ['Hạn mức quét và credit liên quan thế nào?', 'Hạn mức giới hạn số lần quét tính phí (quét đầy đủ / giám sát) mỗi tháng, gồm cả quét định kỳ; credit trả cho lần chạy thủ công. Quét định kỳ chỉ dùng hạn mức; chạy thủ công dùng cả hạn mức lẫn credit.'],
    ['Một thương hiệu ở hai thị trường?', 'Một dự án = một thương hiệu × một thị trường. Hai thị trường là hai dự án, mỗi dự án có thư viện câu hỏi, bộ đối thủ và điểm riêng; gộp lại sẽ che lấp nhau.'],
    ['Việc sửa lỗi (sửa website, đăng bài, bách khoa) có trong phí tháng không?', 'Sản phẩm bàn giao thì có: bản thảo sẵn đăng, JSON-LD, bộ đăng tải. Việc đăng, gửi bài và biên tập do đội của bạn hoặc agency thực hiện. Buổi tư vấn của Scale giúp xếp ưu tiên, không thay thế thực thi.'],
    ['Chứng minh hiệu quả thế nào?', 'Với bộ câu hỏi cố định, thay đổi tỷ lệ xuất hiện ở các câu được sửa trừ thay đổi ở các câu còn lại = hiệu quả sửa lỗi; chỉ báo cáo thay đổi tổng hợp trên 10 điểm. Mỗi bước được ghi vào nhật ký hành động, nền tảng tự xác minh trang đã đăng và quy kết.'],
  ],
};

export interface PageCopy {
  kicker: string; title: string; subtitle: string;
  perMonth: string; perBrand: string; contact: string; subscribe: string; signIn: string; current: string;
  region: { sea: string; us: string };
  compareTitle: string; standardNote: string; standardCta: string;
  guideCta: string;
}

export const PAGE_COPY: Record<PlanLang, PageCopy> = {
  zh: {
    kicker: '套餐 · Credit · 服务项',
    title: '按「品牌 × 市场」订阅,按你的节奏测量',
    subtitle: '三档套餐决定扫描节奏、题库规模、引擎数与交付;定期扫描与报告包含在内,credit 只为「现在就想跑」付费。所有数字与你在工作台看到的一致。',
    perMonth: '/ 月', perBrand: '每品牌 × 市场', contact: '联系我们', subscribe: '进入工作台订阅', signIn: '登录后订阅', current: '当前套餐',
    region: { sea: '东南亚线', us: '美国线(逐州)' },
    compareTitle: '服务项明细', standardNote: '每个指标怎么算、样本量多少、什么算成效——写在公开的《AI 可见度测量标准 v1.1》里,套餐之间只差范围,不差口径。', standardCta: '阅读测量标准 v1.1',
    guideCta: '使用说明与算法白皮书',
  },
  en: {
    kicker: 'Plans · Credits · Service items',
    title: 'Subscribe per brand × market, measure at your cadence',
    subtitle: 'Three plans set the scan cadence, prompt panel size, engines and deliverables; scheduled scans and reports are included, credits only pay for "run it now". Every number here is the number you see in the workspace.',
    perMonth: '/ month', perBrand: 'per brand × market', contact: 'Contact us', subscribe: 'Subscribe in the dashboard', signIn: 'Sign in to subscribe', current: 'Current plan',
    region: { sea: 'Southeast Asia line', us: 'US line (state by state)' },
    compareTitle: 'Service items in detail', standardNote: 'How each metric is computed, sample sizes and what counts as effect are written in the public AI Visibility Measurement Standard v1.1. Plans differ in scope, never in method.', standardCta: 'Read the measurement standard v1.1',
    guideCta: 'User guide & algorithm white paper',
  },
  vi: {
    kicker: 'Gói · Credit · Hạng mục dịch vụ',
    title: 'Đăng ký theo thương hiệu × thị trường, đo theo nhịp của bạn',
    subtitle: 'Ba gói quyết định nhịp quét, quy mô bộ câu hỏi, số engine và sản phẩm bàn giao; quét và báo cáo định kỳ đã bao gồm, credit chỉ trả cho "chạy ngay bây giờ". Mọi con số ở đây đúng như bạn thấy trong workspace.',
    perMonth: '/ tháng', perBrand: 'mỗi thương hiệu × thị trường', contact: 'Liên hệ', subscribe: 'Đăng ký trong bảng điều khiển', signIn: 'Đăng nhập để đăng ký', current: 'Gói hiện tại',
    region: { sea: 'Dòng Đông Nam Á', us: 'Dòng Hoa Kỳ (theo bang)' },
    compareTitle: 'Chi tiết hạng mục dịch vụ', standardNote: 'Cách tính từng chỉ số, cỡ mẫu và thế nào là hiệu quả được viết trong Tiêu chuẩn đo lường khả năng hiển thị AI v1.1 công khai. Các gói khác nhau về phạm vi, không khác về phương pháp.', standardCta: 'Đọc tiêu chuẩn đo lường v1.1',
    guideCta: 'Hướng dẫn sử dụng & sách trắng thuật toán',
  },
};
